/* ==================================================================================================
 * test_crypto.c -- P1.5 (part 1): the core cryptography against the standards and against independent
 * implementations. Every vector is in crypto_vectors.h, generated by tools/gen_crypto_vectors.py:
 * parsed out of the pinned RFC texts, or computed by Python hashlib/hmac, pyca/cryptography (OpenSSL)
 * and argon2-cffi (the Argon2 reference code) at every boundary length the code branches on.
 * ==================================================================================================
 *   K1  helpers: constant-time compare, wipe
 *   K2  SHA-256        independent vectors at every padding boundary; any split of the input streams
 *                      to the same digest
 *   K3  HMAC-SHA-256   RFC 4231 (1-7, the truncated case included); independent vectors over key
 *                      lengths around the block size; streaming
 *   K4  HKDF-SHA-256   RFC 5869 (1-3, PRK and OKM); independent vectors up to the 8160-byte maximum;
 *                      refusals
 *   K5  BLAKE2b        RFC 7693 "abc" and its self-test GRAND HASH (every out length x input length,
 *                      keyed and not); 280 independent vectors; streaming; refusals
 *   K6  Argon2id       RFC 9106 (secret and associated data, 4 lanes); 10 independent vectors across
 *                      passes, memory, lanes and tag lengths; refusals; allocation failure
 *   K7  ChaCha20       RFC 8439 A.1 block vectors and A.2 encryption vectors; in place
 *   K8  Poly1305       RFC 8439 A.3, the eleven vectors (7 of them aimed at reduction corner cases);
 *                      A.4 key generation; streaming
 *   K9  AEAD           RFC 8439 2.8.2 and A.5; 60 independent vectors; EVERY single-byte change to
 *                      key, nonce, AAD, ciphertext or tag refused with the output wiped; in place
 * ============================================================================================== */
#include "engram_test.h"

#include "../src/engram_crypto.h"
#include "../src/engram_rng.h"
#include "crypto_vectors.h"

#include <stdlib.h>
#include <string.h>

#define U8(p) ((const uint8_t *)(p))

static void split_rng(engram_rng *r, size_t n, size_t *a, size_t *b)
{
    *a = n ? (size_t)engram_rng_below(r, n + 1u) : 0u;
    *b = *a + (n - *a ? (size_t)engram_rng_below(r, n - *a + 1u) : 0u);
}

/* ---- K1 ------------------------------------------------------------------------------------------ */
static void test_helpers(void)
{
    uint8_t a[64], b[64];
    unsigned i;
    ET_SECTION("K1: constant-time compare -- equal, and a difference at every position; wipe");
    for (i = 0; i < 64u; i++) a[i] = b[i] = (uint8_t)(i * 37u + 1u);
    ET_CHECK(engram_ct_equal(a, b, 64u));
    ET_CHECK(engram_ct_equal(a, b, 0u));
    for (i = 0; i < 64u; i++) {
        b[i] ^= 0x80u;
        ET_CHECK(!engram_ct_equal(a, b, 64u));
        b[i] ^= 0x80u;
    }
    engram_wipe(a, sizeof a);
    for (i = 0; i < 64u; i++) ET_CHECK(a[i] == 0u);
    engram_wipe(NULL, 5u);
}

/* ---- K2, K3, K4 ------------------------------------------------------------------------------------ */
static void test_sha_hmac_hkdf(void)
{
    static const uint8_t zero32[32];                     /* RFC 5869: an absent salt is HashLen zeros */
    static uint8_t okm[8160];
    uint8_t d[32], prk[32];
    engram_rng r;
    size_t i, a, b, bad = 0, bad_split = 0;
    engram_rng_seed(&r, 0x5A256u);

    ET_SECTION("K2: SHA-256 -- independent vectors at every padding boundary; every split streams alike");
    for (i = 0; i < X_SHA256_N; i++) {
        const cv_t *v = &x_sha256[i];
        engram_sha256_ctx c;
        unsigned k;
        engram_sha256(v->a, v->na, d);
        if (memcmp(d, v->b, 32u)) bad++;
        for (k = 0; k < 8u; k++) {
            split_rng(&r, v->na, &a, &b);
            engram_sha256_init(&c);
            engram_sha256_update(&c, v->a, a);
            engram_sha256_update(&c, v->a + a, b - a);
            engram_sha256_update(&c, v->a + b, v->na - b);
            engram_sha256_final(&c, d);
            if (memcmp(d, v->b, 32u)) bad_split++;
        }
    }
    printf("       %lu inputs of 0..1000 bytes\n", (unsigned long)X_SHA256_N);
    ET_EQ_U64(bad, 0u);
    ET_EQ_U64(bad_split, 0u);

    ET_SECTION("K3: HMAC-SHA-256 -- RFC 4231 test cases 1-7; independent vectors across key lengths");
    bad = 0;
    for (i = 0; i < RFC4231_HMAC_N; i++) {
        const cv_t *v = &rfc4231_hmac[i];
        engram_hmac(v->a, v->na, v->b, v->nb, d);
        if (v->nc < 16u || v->nc > 32u || memcmp(d, v->c, v->nc)) bad++;   /* case 5: truncated to 128 */
    }
    ET_EQ_U64(RFC4231_HMAC_N, 7u);
    ET_EQ_U64(bad, 0u);
    bad = 0; bad_split = 0;
    for (i = 0; i < X_HMAC_N; i++) {
        const cv_t *v = &x_hmac[i];
        engram_hmac_ctx c;
        engram_hmac(v->a, v->na, v->b, v->nb, d);
        if (memcmp(d, v->c, 32u)) bad++;
        split_rng(&r, v->nb, &a, &b);
        engram_hmac_init(&c, v->a, v->na);
        engram_hmac_update(&c, v->b, a);
        engram_hmac_update(&c, v->b + a, v->nb - a);
        engram_hmac_final(&c, d);
        if (memcmp(d, v->c, 32u)) bad_split++;
    }
    printf("       %lu independent vectors, keys of 0..131 bytes\n", (unsigned long)X_HMAC_N);
    ET_EQ_U64(bad, 0u);
    ET_EQ_U64(bad_split, 0u);

    ET_SECTION("K4: HKDF-SHA-256 -- RFC 5869 A.1-A.3 (PRK and OKM); independent vectors to 8160 bytes");
    bad = 0;
    for (i = 0; i < RFC5869_HKDF_N; i++) {
        const cv_t *v = &rfc5869_hkdf[i];
        engram_hmac(v->nb ? v->b : zero32,
                    v->nb ? v->nb : 32u, v->a, v->na, prk);
        if (memcmp(prk, v->d, 32u)) bad++;
        if (engram_hkdf(v->b, v->nb, v->a, v->na, v->c, v->nc, okm, v->x) != ENGRAM_OK || v->x != v->ne ||
            memcmp(okm, v->e, v->x)) bad++;
    }
    ET_EQ_U64(RFC5869_HKDF_N, 3u);
    ET_EQ_U64(bad, 0u);
    bad = 0;
    for (i = 0; i < X_HKDF_N; i++) {
        const cv_t *v = &x_hkdf[i];
        if (engram_hkdf(v->b, v->nb, v->a, v->na, v->c, v->nc, okm, v->x) != ENGRAM_OK || memcmp(okm, v->e, v->x)) bad++;
    }
    ET_EQ_U64(bad, 0u);
    ET_RC(engram_hkdf(NULL, 0, "k", 1u, NULL, 0, okm, 8161u), ENGRAM_E_ARG);
    ET_RC(engram_hkdf(NULL, 3u, "k", 1u, NULL, 0, okm, 32u), ENGRAM_E_ARG);
    ET_RC(engram_hkdf(NULL, 0, "k", 1u, NULL, 0, NULL, 32u), ENGRAM_E_ARG);
    ET_OK(engram_hkdf(NULL, 0, "k", 1u, NULL, 0, okm, 8160u));
}

/* ---- K5 --------------------------------------------------------------------------------------------- */
static void selftest_seq(uint8_t *out, size_t len, uint32_t seed)     /* RFC 7693 Appendix E */
{
    size_t i;
    uint32_t t, a = 0xDEAD4BADu * seed, b = 1u;
    for (i = 0; i < len; i++) { t = a + b; a = b; b = t; out[i] = (uint8_t)(t >> 24); }
}

static void test_blake2b(void)
{
    static const size_t md_len[4] = { 20u, 32u, 48u, 64u }, in_len[6] = { 0u, 3u, 128u, 129u, 255u, 1024u };
    uint8_t in[1024], md[64], key[64];
    engram_blake2b_ctx grand, c;
    engram_rng r;
    size_t i, j, a, b, bad = 0, bad_split = 0;
    ET_SECTION("K5: BLAKE2b -- RFC 7693: \"abc\", and the self-test grand hash over every length, keyed and not");
    ET_OK(engram_blake2b(md, 64u, NULL, 0, "abc", 3u));
    ET_CHECK(memcmp(md, rfc7693_blake2b[0].b, 64u) == 0);
    ET_OK(engram_blake2b_init(&grand, 32u, NULL, 0));
    for (i = 0; i < 4u; i++)
        for (j = 0; j < 6u; j++) {
            selftest_seq(in, in_len[j], (uint32_t)in_len[j]);
            ET_OK(engram_blake2b(md, md_len[i], NULL, 0, in, in_len[j]));
            engram_blake2b_update(&grand, md, md_len[i]);
            selftest_seq(key, md_len[i], (uint32_t)md_len[i]);
            ET_OK(engram_blake2b(md, md_len[i], key, md_len[i], in, in_len[j]));
            engram_blake2b_update(&grand, md, md_len[i]);
        }
    engram_blake2b_final(&grand, md);
    ET_CHECK(memcmp(md, rfc7693_blake2b[0].c, 32u) == 0);

    ET_SECTION("K5: BLAKE2b -- independent vectors: out 1..64 x key 0..64 x input 0..1000; streaming; refusals");
    engram_rng_seed(&r, 0xB2Bu);
    for (i = 0; i < X_BLAKE2B_N; i++) {
        const cv_t *v = &x_blake2b[i];
        if (engram_blake2b(md, v->x, v->a, v->na, v->b, v->nb) != ENGRAM_OK || memcmp(md, v->c, v->x)) bad++;
        split_rng(&r, v->nb, &a, &b);
        if (engram_blake2b_init(&c, v->x, v->a, v->na) != ENGRAM_OK) { bad_split++; continue; }
        engram_blake2b_update(&c, v->b, a);
        engram_blake2b_update(&c, v->b + a, b - a);
        engram_blake2b_update(&c, v->b + b, v->nb - b);
        engram_blake2b_final(&c, md);
        if (memcmp(md, v->c, v->x)) bad_split++;
    }
    printf("       %lu independent vectors\n", (unsigned long)X_BLAKE2B_N);
    ET_EQ_U64(bad, 0u);
    ET_EQ_U64(bad_split, 0u);
    ET_RC(engram_blake2b(md, 0u, NULL, 0, "x", 1u), ENGRAM_E_ARG);
    ET_RC(engram_blake2b(md, 65u, NULL, 0, "x", 1u), ENGRAM_E_ARG);
    ET_RC(engram_blake2b(md, 32u, key, 65u, "x", 1u), ENGRAM_E_ARG);
    ET_RC(engram_blake2b(md, 32u, NULL, 3u, "x", 1u), ENGRAM_E_ARG);
    ET_RC(engram_blake2b(NULL, 32u, NULL, 0, "x", 1u), ENGRAM_E_ARG);
}

/* ---- K6 --------------------------------------------------------------------------------------------- */
static void test_argon2id(void)
{
    engram_argon2_params p;
    uint8_t out[1024];
    size_t i, bad = 0;
    uint64_t calls;
    ET_SECTION("K6: Argon2id -- RFC 9106 5.3 (32 KiB, 3 passes, 4 lanes, secret and associated data)");
    {
        const cv_t *v = &rfc9106_argon2id[0];
        p.t_cost = v->x; p.m_kib = v->y; p.lanes = v->z;
        ET_OK(engram_argon2id(&p, v->a, v->na, v->b, v->nb, v->c, v->nc, v->d, v->nd, out, v->u));
        ET_CHECK(v->u == 32u && v->ne == 32u && memcmp(out, v->e, 32u) == 0);
    }
    ET_SECTION("K6: Argon2id -- independent vectors (the reference implementation, via argon2-cffi)");
    for (i = 0; i < X_ARGON2ID_N; i++) {
        const cv_t *v = &x_argon2id[i];
        p.t_cost = v->x; p.m_kib = v->y; p.lanes = v->z;
        if (engram_argon2id(&p, v->a, v->na, v->b, v->nb, NULL, 0, NULL, 0, out, v->u) != ENGRAM_OK ||
            memcmp(out, v->e, v->u)) {
            bad++;
            printf("         t=%u m=%u p=%u tag %u: differs\n", v->x, v->y, v->z, v->u);
        }
    }
    printf("       %lu vectors: passes 1-4, 8 KiB-2 MiB, 1-8 lanes, tags of 4-1024 bytes\n", (unsigned long)X_ARGON2ID_N);
    ET_EQ_U64(bad, 0u);
    ET_SECTION("K6: Argon2id -- refusals wipe the output; an allocation failure is E_MEM, output wiped");
    p.t_cost = 1; p.m_kib = 8; p.lanes = 1;
    memset(out, 0xAB, 32u);
    ET_RC(engram_argon2id(&p, "pw", 2u, "short", 5u, NULL, 0, NULL, 0, out, 32u), ENGRAM_E_ARG);   /* salt < 8 */
    ET_CHECK(out[0] == 0u && out[31] == 0u);
    p.lanes = 2; ET_RC(engram_argon2id(&p, "pw", 2u, "saltsalt", 8u, NULL, 0, NULL, 0, out, 32u), ENGRAM_E_ARG); /* m < 8p */
    p.lanes = 0; ET_RC(engram_argon2id(&p, "pw", 2u, "saltsalt", 8u, NULL, 0, NULL, 0, out, 32u), ENGRAM_E_ARG);
    p.lanes = 1; p.t_cost = 0; ET_RC(engram_argon2id(&p, "pw", 2u, "saltsalt", 8u, NULL, 0, NULL, 0, out, 32u), ENGRAM_E_ARG);
    p.t_cost = 1; ET_RC(engram_argon2id(&p, "pw", 2u, "saltsalt", 8u, NULL, 0, NULL, 0, out, 3u), ENGRAM_E_ARG);
    ET_RC(engram_argon2id(&p, NULL, 2u, "saltsalt", 8u, NULL, 0, NULL, 0, out, 32u), ENGRAM_E_ARG);
    ET_RC(engram_argon2id(NULL, "pw", 2u, "saltsalt", 8u, NULL, 0, NULL, 0, out, 32u), ENGRAM_E_ARG);
    memset(out, 0xAB, 32u);
    calls = engram_alloc_calls();
    engram_alloc_fail_at(1);
    ET_RC(engram_argon2id(&p, "pw", 2u, "saltsalt", 8u, NULL, 0, NULL, 0, out, 32u), ENGRAM_E_MEM);
    engram_alloc_fail_at(0);
    ET_CHECK(out[0] == 0u && out[31] == 0u);
    ET_CHECK(engram_alloc_calls() - calls >= 1u);
}

/* ---- K7, K8 -------------------------------------------------------------------------------------------- */
static void test_chacha_poly(void)
{
    uint8_t blk[64], buf[1024], tag[16];
    engram_poly1305_ctx pc;
    engram_rng r;
    size_t i, bad = 0, bad_split = 0, a, b;
    ET_SECTION("K7: ChaCha20 -- RFC 8439 A.1 block function (5) and A.2 encryption (3), in place too");
    for (i = 0; i < RFC8439_BLOCK_N; i++) {
        const cv_t *v = &rfc8439_block[i];
        engram_chacha20_block(U8(v->a), v->x, U8(v->b), blk);
        if (memcmp(blk, v->c, 64u)) bad++;
    }
    ET_EQ_U64(RFC8439_BLOCK_N, 5u);
    for (i = 0; i < RFC8439_ENC_N; i++) {
        const cv_t *v = &rfc8439_enc[i];
        engram_chacha20_xor(U8(v->a), v->x, U8(v->b), U8(v->c), buf, v->nc);
        if (memcmp(buf, v->d, v->nc)) bad++;
        memcpy(buf, v->c, v->nc);
        engram_chacha20_xor(U8(v->a), v->x, U8(v->b), buf, buf, v->nc);
        if (memcmp(buf, v->d, v->nc)) bad++;
    }
    ET_EQ_U64(RFC8439_ENC_N, 3u);
    ET_EQ_U64(bad, 0u);

    ET_SECTION("K8: Poly1305 -- RFC 8439 A.3 (11, the reduction's corners included) and A.4 key generation");
    bad = 0;
    engram_rng_seed(&r, 0x9013u);
    for (i = 0; i < RFC8439_POLY_N; i++) {
        const cv_t *v = &rfc8439_poly[i];
        engram_poly1305(U8(v->a), U8(v->b), v->nb, tag);
        if (memcmp(tag, v->c, 16u)) { bad++; printf("         A.3 vector #%lu differs\n", (unsigned long)i + 1u); }
        split_rng(&r, v->nb, &a, &b);
        engram_poly1305_init(&pc, U8(v->a));
        engram_poly1305_update(&pc, v->b, a);
        engram_poly1305_update(&pc, v->b + a, b - a);
        engram_poly1305_update(&pc, v->b + b, v->nb - b);
        engram_poly1305_final(&pc, tag);
        if (memcmp(tag, v->c, 16u)) bad_split++;
    }
    ET_EQ_U64(RFC8439_POLY_N, 11u);
    ET_EQ_U64(bad, 0u);
    ET_EQ_U64(bad_split, 0u);
    bad = 0;
    for (i = 0; i < RFC8439_KEYGEN_N; i++) {
        const cv_t *v = &rfc8439_keygen[i];
        engram_chacha20_block(U8(v->a), 0u, U8(v->b), blk);
        if (memcmp(blk, v->c, 32u)) bad++;
    }
    ET_EQ_U64(bad, 0u);
}

/* ---- K9 --------------------------------------------------------------------------------------------- */
static int all_zero(const uint8_t *p, size_t n)
{
    size_t i;
    for (i = 0; i < n; i++) if (p[i]) return 0;
    return 1;
}

static void test_aead(void)
{
    static uint8_t ct[1024], pt[1024], key[32], nonce[12], aad[128], tg[16], buf[1024];
    size_t i, bad = 0, tamper = 0, tamper_bad = 0;
    ET_SECTION("K9: AEAD_CHACHA20_POLY1305 -- RFC 8439 2.8.2 (seal) and A.5 (open); in place");
    for (i = 0; i < RFC8439_AEAD_N; i++) {
        const cv_t *v = &rfc8439_aead[i];                /* a key, b nonce, c aad, d pt, e ct, f tag */
        engram_aead_seal(U8(v->a), U8(v->b), v->c, v->nc, U8(v->d), v->nd, ct, tg);
        if (memcmp(ct, v->e, v->ne) || memcmp(tg, v->f, 16u)) bad++;
        if (engram_aead_open(U8(v->a), U8(v->b), v->c, v->nc, U8(v->e), v->ne, U8(v->f), pt) != ENGRAM_OK ||
            memcmp(pt, v->d, v->nd)) bad++;
        memcpy(buf, v->d, v->nd);                        /* in place, both ways */
        engram_aead_seal(U8(v->a), U8(v->b), v->c, v->nc, buf, v->nd, buf, tg);
        if (memcmp(buf, v->e, v->ne)) bad++;
        if (engram_aead_open(U8(v->a), U8(v->b), v->c, v->nc, buf, v->ne, tg, buf) != ENGRAM_OK ||
            memcmp(buf, v->d, v->nd)) bad++;
    }
    ET_EQ_U64(RFC8439_AEAD_N, 2u);
    ET_EQ_U64(bad, 0u);

    ET_SECTION("K9: AEAD -- independent vectors (OpenSSL via pyca/cryptography): AAD 0..100 x text 0..1000");
    bad = 0;
    for (i = 0; i < X_AEAD_N; i++) {
        const cv_t *v = &x_aead[i];
        engram_aead_seal(U8(v->a), U8(v->b), v->c, v->nc, U8(v->d), v->nd, ct, tg);
        if ((v->nd && memcmp(ct, v->e, v->nd)) || memcmp(tg, v->f, 16u)) bad++;
        if (engram_aead_open(U8(v->a), U8(v->b), v->c, v->nc, U8(v->e), v->ne, U8(v->f), pt) != ENGRAM_OK ||
            (v->nd && memcmp(pt, v->d, v->nd))) bad++;
    }
    printf("       %lu vectors\n", (unsigned long)X_AEAD_N);
    ET_EQ_U64(bad, 0u);

    ET_SECTION("K9: AEAD -- every single-bit change to key, nonce, AAD, ciphertext or tag is refused, output wiped");
    {
        const cv_t *v = &rfc8439_aead[1];                /* 2.8.2: 114 bytes of text, 12 of AAD */
        size_t n = v->nd, na = v->nc, f, j;
        for (f = 0; f < 5u; f++) {
            size_t len = f == 0 ? 32u : f == 1 ? 12u : f == 2 ? na : f == 3 ? n : 16u;
            for (j = 0; j < len; j++) {
                memcpy(key, v->a, 32u); memcpy(nonce, v->b, 12u); memcpy(aad, v->c, na);
                memcpy(ct, v->e, n); memcpy(tg, v->f, 16u);
                (f == 0 ? key : f == 1 ? nonce : f == 2 ? aad : f == 3 ? ct : tg)[j] ^= (uint8_t)(1u << (j % 8u));
                memset(pt, 0xAA, n);
                tamper++;
                if (engram_aead_open(key, nonce, aad, na, ct, n, tg, pt) != ENGRAM_E_AUTH || !all_zero(pt, n)) tamper_bad++;
            }
        }
        printf("       %lu altered messages, each refused\n", (unsigned long)tamper);
        ET_EQ_U64(tamper_bad, 0u);
        ET_CHECK(tamper == 32u + 12u + na + n + 16u);
    }
}

int main(void)
{
    printf("ENGRAM P1.5 -- core cryptography\n");
    ET_SELFTEST();
    test_helpers();
    test_sha_hmac_hkdf();
    test_blake2b();
    test_argon2id();
    test_chacha_poly();
    test_aead();
    return et_report("test_crypto");
}
