#!/usr/bin/env python3
"""
gen_expert_vectors.py -- freeze what the expert's forward pass (engram_expert.c) must compute, from the
independent Python implementation of the pass as engram_expert.h specifies it (tools/ref_expert.py:
every float32 operation in numpy float32, every double one in Python floats, the integer products in
int64, exp and log2 restated operation for operation, the Cascade initialisation and the context hashes
from their own specifications).

Per case: the configuration, the gains and biases (set to a fixed pattern of exact binary fractions, so
the gain and bias arithmetic is exercised, not multiplied by 1 and added to 0), and for a text:
the bits of every position, and the logits of three positions.

Usage: tools/gen_expert_vectors.py test/expert_vectors.h      (python3 with numpy)
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import ref_expert as R  # noqa: E402


TEXT = ("Memory is the treasury and guardian of all things. — Cicero; "
        "été, naïve, 十二月. 12:34 -- ok!").encode("utf-8")

CASES = [  # width, hidden, orders, buckets_log2, K, seed
    (32, 0, 3, 6, 16, 11),
    (48, 1, 4, 5, 4, 12),
    (64, 2, 6, 7, 64, 13),
    (16, 0, 1, 4, 16, 14),
    (512, 0, 6, 12, 16, 0x534C4F57),       # the default: P2.1.1's choice
]


def main(out):
    L = ["/* GENERATED by tools/gen_expert_vectors.py -- DO NOT EDIT.",
         " * The expert's forward pass, computed by an independent Python implementation of engram_expert.h. */",
         "#ifndef ENGRAM_EXPERT_VECTORS_H", "#define ENGRAM_EXPERT_VECTORS_H",
         "static const uint8_t expert_text[] = { %s };" % ",".join(str(b) for b in TEXT),
         "#define EXPERT_TEXT_N %du" % len(TEXT),
         "typedef struct { unsigned width, hidden, orders, blog2, K; uint64_t seed;",
         "                 const double *bits; const unsigned *lpos; const float *logits; } expert_case;"]
    rows = []
    for ci, (W, hid, orders, blog2, K, seed) in enumerate(CASES):
        e = R.Expert(W, hid, orders, blog2, K, seed)
        e.set_pattern()
        bits = [R.Expert.softmax_bits(e.forward(TEXT, t)["logits"], TEXT[t])[1] for t in range(len(TEXT))]
        lpos = [0, len(TEXT) // 2, len(TEXT)]
        lg = []
        for t in lpos: lg += e.forward(TEXT, t)["logits"]
        L.append("static const double ev%d_bits[] = { %s };" % (ci, ",".join(repr(b) for b in bits)))
        L.append("static const unsigned ev%d_lpos[] = { %s };" % (ci, ",".join("%du" % p for p in lpos)))
        L.append("static const float ev%d_logits[] = { %s };" % (ci, ",".join(repr(float(x)) + "f" if float(x) != 0.0 else "0.0f" for x in lg)))
        rows.append("    { %du, %du, %du, %du, %du, 0x%Xull, ev%d_bits, ev%d_lpos, ev%d_logits }," % (W, hid, orders, blog2, K, seed, ci, ci, ci))
        print("case %d: %d bits over %d bytes" % (ci, round(sum(bits)), len(TEXT)), file=sys.stderr)
    L.append("static const expert_case expert_cases[] = {")
    L += rows
    L += ["};", "#define EXPERT_CASES_N (sizeof expert_cases / sizeof expert_cases[0])", "#endif"]
    open(out, "w", newline="\n").write("\n".join(L) + "\n")
    print("wrote %s" % out)


if __name__ == "__main__":
    main(sys.argv[1])
