#!/usr/bin/env python3
"""
gen_cascade_vectors.py -- freeze what the C Cascade weight (engram_cascade.c) must compute, from an
independent Python implementation of its specification (engram_cascade.h).

The reference is written from the header's words, not from the C: numpy float32 scalars for every
float32 operation the spec names, Python floats (IEEE doubles) for the double ones, integers for the
hash. It is also the research prototype's update (research/cascade_weight/cascade.py) restated with
the row sum in double and in index order -- the one place the prototype's numpy pairwise sum is not a
specification anything else can reproduce.

For each case: a shape, K, kappa, seed; the initial positions; then a sequence of updates, each from a
gradient derived from SHA-256 (so the generator is deterministic), and the positions after each.

Usage: tools/gen_cascade_vectors.py test/cascade_vectors.h   (python3 with numpy)
"""
import hashlib
import struct
import sys

import numpy as np

F32 = np.float32
M64 = (1 << 64) - 1


def mix64(x):
    x = (x + 0x9E3779B97F4A7C15) & M64
    x = ((x ^ (x >> 30)) * 0xBF58476D1CE4E5B9) & M64
    x = ((x ^ (x >> 27)) * 0x94D049BB133111EB) & M64
    return x ^ (x >> 31)


def uniform(seed, step, index):
    base = mix64((seed * 0x9E3779B97F4A7C15 + step) & M64)
    return F32(mix64(index ^ base) >> 40) * F32(1.0 / 16777216.0)


# engram_exp2, restated (Python floats are IEEE doubles; the operations are the same, in the same order)
def pow2i(k):
    if k > 1023: return float("inf")
    if k >= -1022: return struct.unpack("<d", struct.pack("<Q", (k + 1023) << 52))[0]
    if k >= -1074: return struct.unpack("<d", struct.pack("<Q", 1 << (k + 1074)))[0]
    return 0.0


def eround(x):
    t = -x if x < 0 else x
    i = int(t)
    r = float(i)
    if t - r >= 0.5: r += 1.0
    return -r if x < 0 else r


def exp_poly(r):
    p = 1.0 / 6227020800.0
    for c in (1.0 / 479001600.0, 1.0 / 39916800.0, 1.0 / 3628800.0, 1.0 / 362880.0, 1.0 / 40320.0,
              1.0 / 5040.0, 1.0 / 720.0, 1.0 / 120.0, 1.0 / 24.0, 1.0 / 6.0, 0.5, 1.0, 1.0):
        p = p * r + c
    return p


def scale(p, k):
    if k < -1021: return (p * pow2i(k + 1000)) * pow2i(-1000)
    if k > 1023: return (p * pow2i(k - 1)) * 2.0
    return p * pow2i(k)


def exp2(x):
    LN2 = 6.93147180559945286227e-01
    if x >= 1024.0: return float("inf")
    if x < -1075.0: return 0.0
    kd = eround(x)
    return scale(exp_poly((x - kd) * LN2), int(kd))


def value(p, K): return int(p >= 2 * K) - int(p < K)
def depth(p, K): return K - 1 - p if p < K else (p - 2 * K if p >= 2 * K else p - K)


def init(rows, cols, K, seed):
    pos = []
    for i in range(rows * cols):
        u = uniform(seed, 0xFFFFFFFF, i) * F32(3 * K)
        p = int(u)
        pos.append(min(p, 3 * K - 1))
    return pos


def update(pos, g, rows, cols, K, kappa, seed, step, lr):
    meta = [F32(exp2(-float(F32(kappa)) * d * 4.0 / K)) for d in range(K)]
    lr = F32(lr)
    out = list(pos)
    moved = flipped = 0
    for r in range(rows):
        ss = 0.0
        for c in range(cols):
            gv = float(g[r * cols + c])
            ss += gv * gv
        inv = F32(1.0 / ((ss / cols) ** 0.5 + 1e-12))       # sqrt is correctly rounded in both languages
        for c in range(cols):
            u = (-lr * g[r * cols + c]) * inv
            mag = -u if u < 0 else u
            if mag > F32(K): mag = F32(K)
            if mag == 0: continue
            p = out[r * cols + c]
            up = u > 0
            v = value(p, K)
            if (v > 0 and not up) or (v < 0 and up): mag = mag * meta[depth(p, K)]
            whole = F32(np.floor(mag))
            steps = int(whole) + (1 if uniform(seed, step, r * cols + c) < mag - whole else 0)
            if not steps: continue
            q = min(p + steps, 3 * K - 1) if up else max(p - steps, 0)
            if q != p:
                moved += 1
                if value(q, K) != v: flipped += 1
                out[r * cols + c] = q
    return out, moved, flipped


def grad(label, n, magnitude):
    raw, c = b"", 0
    while len(raw) < 4 * n:
        raw += hashlib.sha256(("%s/%d" % (label, c)).encode()).digest(); c += 1
    ints = struct.unpack("<%di" % n, raw[:4 * n])
    g = [F32(x / 2147483648.0) * F32(magnitude) for x in ints]
    for i in range(0, n, 7): g[i] = F32(0.0)                  # exact zeros: they must move nothing
    return g


def main(out):
    L = ["/* GENERATED by tools/gen_cascade_vectors.py -- DO NOT EDIT.",
         " * The Cascade weight, computed by an independent Python implementation of engram_cascade.h. */",
         "#ifndef ENGRAM_CASCADE_VECTORS_H", "#define ENGRAM_CASCADE_VECTORS_H",
         "typedef struct { uint32_t rows, cols, K; float kappa, lr; uint64_t seed; unsigned steps;",
         "                 const uint8_t *init; const float *grads; const uint8_t *after; const uint32_t *moved, *flipped; } cascade_case;"]
    cases = []
    spec = [(3, 5, 4, 0.0, 1.0, 1), (4, 16, 16, 0.5, 1.0, 7), (2, 64, 16, 0.5, 0.3, 11), (5, 9, 64, 1.0, 3.0, 13),
            (1, 1, 16, 0.5, 1.0, 17), (8, 33, 16, 2.0, 5.0, 19), (6, 7, 4, 0.25, 0.1, 23), (3, 128, 64, 0.5, 20.0, 29)]
    for ci, (rows, cols, K, kappa, lr, seed) in enumerate(spec):
        pos = init(rows, cols, K, seed)
        steps = 6
        gs, afters, moved, flipped = [], [], [], []
        for s in range(1, steps + 1):
            mag = [0.001, 1.0, 1000.0, 1e-30, 3.0, 0.5][s - 1]
            g = grad("cg/%d/%d" % (ci, s), rows * cols, mag)
            pos, mv, fl = update(pos, g, rows, cols, K, kappa, seed, s, lr)
            gs += g; afters += pos; moved.append(mv); flipped.append(fl)
        name = "cv%d" % ci
        L.append("static const uint8_t %s_init[] = { %s };" % (name, ",".join(str(x) for x in init(rows, cols, K, seed))))
        L.append("static const float %s_grads[] = { %s };" % (name, ",".join(repr(float(x)) + "f" if float(x) != 0 else "0.0f" for x in gs)))
        L.append("static const uint8_t %s_after[] = { %s };" % (name, ",".join(str(x) for x in afters)))
        L.append("static const uint32_t %s_moved[] = { %s };" % (name, ",".join("%du" % x for x in moved)))
        L.append("static const uint32_t %s_flipped[] = { %s };" % (name, ",".join("%du" % x for x in flipped)))
        cases.append("    { %du, %du, %du, %sf, %sf, %du, %du, %s_init, %s_grads, %s_after, %s_moved, %s_flipped }," %
                     (rows, cols, K, repr(float(kappa)), repr(float(lr)), seed, steps, name, name, name, name, name))
    L.append("static const cascade_case cascade_cases[] = {")
    L.extend(cases)
    L.append("};")
    L.append("#define CASCADE_CASES_N (sizeof cascade_cases / sizeof cascade_cases[0])")
    L.append("#endif")
    open(out, "w", newline="\n").write("\n".join(L) + "\n")
    print("wrote %s" % out)


if __name__ == "__main__":
    main(sys.argv[1])
