#!/usr/bin/env python3
"""
gen_grad_vectors.py -- freeze what the expert's backward pass (engram_expert.c) must compute, from the
independent Python implementation of engram_expert.h's "THE BACKWARD PASS, EXACTLY" in tools/ref_expert.py.

It first proves two things and refuses to write a single vector if either fails:
  1. the backward FORMULAS: tools/ref_expert.py's float64 shadow network, against central finite
     differences of its loss, for hidden 0, 1 and 2 -- and a planted error in one formula must be caught
     (a check that cannot fail proves nothing, R6);
  2. the vectorised initial draw the default expert needs equals the scalar one, weight for weight.

Per case: the configuration, a batch of positions (repeats, position 0, the last byte), and the backward
pass's results bit for bit: the loss (a double's bits), the gradients of the bias and every gain (floats'
bits), and of the head, the hidden layers and the bag rows -- in full where small, always as an FNV-1a
hash of their bytes.

Usage: tools/gen_grad_vectors.py test/grad_vectors.h      (python3 with numpy; about a minute)
"""
import os
import struct
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import ref_expert as R  # noqa: E402

F32 = np.float32

TEXT = ("Memory is the treasury and guardian of all things. — Cicero; "
        "été, naïve, 十二月. 12:34 -- ok!").encode("utf-8")

# width, hidden, orders, buckets_log2, K, seed, pattern, positions. Pattern 0: the gains and biases an expert
# opens with (1 and 0); 1: exact binary fractions; 2: the same with every fifth gain negative
CASES = [
    (32, 0, 3, 4, 16, 21, 1, [5, 0, 17, 5, 40]),                        # a repeated position, position 0
    (32, 1, 4, 4, 4, 22, 2, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]),        # 16 buckets: features shared
    (16, 2, 2, 4, 64, 23, 2, [len(TEXT) - 1, 30, 31]),                   # W < 256; two hidden layers
    (48, 0, 6, 5, 16, 24, 0, [12, 60, 61]),
    (48, 1, 1, 4, 16, 25, 1, [9]),                                       # B = 1; one order
    (512, 0, 6, 12, 16, 0x534C4F57, 0, [0, 70, 71, 72]),                # the default expert: P2.1.1's choice
]
FULL_MAX = 24000          # matrices up to this many elements are written in full, larger ones as a hash


def bits32(a):
    return [struct.unpack("<I", struct.pack("<f", float(x)))[0] for x in np.asarray(a, F32).ravel()]


def fnv(words):
    h = 0xCBF29CE484222325
    for w in words:
        for k in range(4):
            h ^= (w >> (8 * k)) & 0xFF
            h = (h * 0x100000001B3) & 0xFFFFFFFFFFFFFFFF
    return h


def hexlist(ws):
    return ",".join("0x%08Xu" % w for w in ws)


def prove():
    planted = R.shadow_gradcheck(hidden=1, plant=True)
    if not max(planted.values()) > 1.0:
        sys.exit("REFUSED: the gradient check did not catch a planted error: it cannot fail")
    for hid in (0, 1, 2):
        w = R.shadow_gradcheck(hidden=hid)
        print("shadow gradient check, hidden %d: worst %.3f of tolerance" % (hid, max(w.values())), file=sys.stderr)
        if max(w.values()) > 1.0:
            sys.exit("REFUSED: the backward formulas disagree with finite differences: %r" % w)
    for rows, cols, K, seed in ((7, 33, 16, 5), (64, 48, 4, 0x534C4F57), (3, 512, 64, 99)):
        if not np.array_equal(R.cascade_positions(rows, cols, K, seed), R.cascade_positions_scalar(rows, cols, K, seed)):
            sys.exit("REFUSED: the vectorised initial draw differs from the scalar one")


def valid(W, hid, orders, blog2, K):
    """engram_expert_cfg_check's ranges: a vector for a configuration the C refuses would test nothing"""
    return 16 <= W <= 4096 and W % 16 == 0 and 0 <= hid <= 4 and 1 <= orders <= 16 and 4 <= blog2 <= 20 and K in (4, 16, 64)


def main(out):
    for c in CASES:
        if not valid(*c[:5]): sys.exit("REFUSED: case %r is outside what engram_expert_cfg_check accepts" % (c[:6],))
    prove()
    L = ["/* GENERATED by tools/gen_grad_vectors.py -- DO NOT EDIT.",
         " * The expert's backward pass, computed by the Python implementation of engram_expert.h in",
         " * tools/ref_expert.py, whose formulas were first checked against finite differences. Floats and",
         " * doubles as their bits; large matrices as FNV-1a-64 of their bytes (little-endian). */",
         "#ifndef ENGRAM_GRAD_VECTORS_H", "#define ENGRAM_GRAD_VECTORS_H",
         "static const uint8_t grad_text[] = { %s };" % ",".join(str(b) for b in TEXT),
         "#define GRAD_TEXT_N %du" % len(TEXT),
         "typedef struct {",
         "    unsigned width, hidden, orders, blog2, K; uint64_t seed; int pattern;   /* 0 as opened, 1, 2 signed */",
         "    unsigned B; const unsigned *pos; uint64_t bits;",
         "    const uint32_t *bias, *gain;                  /* 256, (hidden + 1) * width + 256 */",
         "    const uint32_t *head; uint64_t head_h;        /* head NULL when only hashed */",
         "    const uint32_t *hid; uint64_t hid_h;          /* the hidden layers, concatenated */",
         "    unsigned n_feat; const uint32_t *feat; const uint32_t *bag; uint64_t bag_h;",
         "} grad_case;"]
    rows = []
    for ci, (W, hid, orders, blog2, K, seed, pattern, pos) in enumerate(CASES):
        e = R.Expert(W, hid, orders, blog2, K, seed)
        if pattern: e.set_pattern(signed=pattern == 2)
        bits, g = R.Expert.backward(e, TEXT, pos)
        feat = sorted(g["bag"])
        bag = [w for f in feat for w in bits32(g["bag"][f])]
        head = bits32(g["head"])
        hidw = [w for m in g["hid"] for w in bits32(m)]
        n = "gv%d" % ci
        L.append("static const unsigned %s_pos[] = { %s };" % (n, ",".join("%du" % p for p in pos)))
        L.append("static const uint32_t %s_bias[] = { %s };" % (n, hexlist(bits32(g["bias"]))))
        L.append("static const uint32_t %s_gain[] = { %s };" % (n, hexlist(bits32(g["gain"]))))
        L.append("static const uint32_t %s_feat[] = { %s };" % (n, ",".join("%du" % f for f in feat)))
        full_head = len(head) <= FULL_MAX
        full_hid = 0 < len(hidw) <= FULL_MAX
        full_bag = len(bag) <= FULL_MAX
        if full_head: L.append("static const uint32_t %s_head[] = { %s };" % (n, hexlist(head)))
        if full_hid: L.append("static const uint32_t %s_hid[] = { %s };" % (n, hexlist(hidw)))
        if full_bag: L.append("static const uint32_t %s_bag[] = { %s };" % (n, hexlist(bag)))
        rows.append("    { %du, %du, %du, %du, %du, 0x%Xull, %d, %du, %s_pos, 0x%016Xull, %s_bias, %s_gain, "
                    "%s, 0x%016Xull, %s, 0x%016Xull, %du, %s_feat, %s, 0x%016Xull }," %
                    (W, hid, orders, blog2, K, seed, int(pattern), len(pos), n,
                     struct.unpack("<Q", struct.pack("<d", bits))[0], n, n,
                     n + "_head" if full_head else "NULL", fnv(head),
                     n + "_hid" if full_hid else "NULL", fnv(hidw),
                     len(feat), n, n + "_bag" if full_bag else "NULL", fnv(bag)))
        print("case %d: W %d hidden %d, B %d: %.4f bits, %d features" % (ci, W, hid, len(pos), bits, len(feat)),
              file=sys.stderr)
    L.append("static const grad_case grad_cases[] = {")
    L += rows
    L += ["};", "#define GRAD_CASES_N (sizeof grad_cases / sizeof grad_cases[0])", "#endif"]
    open(out, "w", newline="\n").write("\n".join(L) + "\n")
    print("wrote %s" % out)


if __name__ == "__main__":
    main(sys.argv[1])
